version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew check jacocoTestReport javadoc jar
      - run: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
            - ~/work/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_artifacts:
          path: build/docs
          destination: docs
      - store_artifacts:
          path: build/libs
          destination: libs
      - store_test_results:
          path: build/test-results
  package:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          key: m2-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths: 
            - ~/.m2
          key: m2-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/apidocs
          destination: apidocs
      - store_artifacts: 
          path: target/libs
          destination: libs
      - store_test_results:
          path: target/surefire-reports
workflows:
  version: 2
  build_and_package:
    jobs:
      - build
      - package